# Generated by Django 4.2.5 on 2023-09-21 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_paciente', models.BigIntegerField()),
                ('diagnostico', models.TextField()),
                ('motivo', models.CharField(max_length=255)),
                ('tratamiento', models.CharField(max_length=255)),
                ('medicacion', models.CharField(max_length=255)),
                ('fecha_antec', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')])),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_enfermero', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')])),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_llamada',
            fields=[
                ('id_tipo_llamada', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_llamada', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_paciente', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('patologia', models.CharField(blank=True, max_length=255)),
                ('alergias', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('dni_enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.enfermero')),
            ],
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id_llamada', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('fecha_hora_llamada', models.DateTimeField()),
                ('fecha_hora_atendida', models.DateTimeField()),
                ('dni_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Area_llamada',
            fields=[
                ('id_area_llamada', models.AutoField(primary_key=True, serialize=False)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
                ('id_llamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.llamada')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='dni_enfermero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.enfermero'),
        ),
        migrations.AddField(
            model_name='area',
            name='dni_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AddField(
            model_name='area',
            name='id_tipo_llamada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_llamada'),
        ),
    ]
